networks:
  TOR_NETWORK:
    driver: bridge
    ipam:
      config:
      - subnet: 192.0.0.0/8
services:
  node1:
    container_name: node1
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.16.102.233
    ports:
    - 9050:9050
    - 9051:9051
  node10:
    container_name: node10
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.69.118.113
    ports:
    - 9068:9050
    - 9069:9051
  node2:
    container_name: node2
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.182.139.32
    ports:
    - 9052:9050
    - 9053:9051
  node3:
    container_name: node3
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.139.59.189
    ports:
    - 9054:9050
    - 9055:9051
  node4:
    container_name: node4
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.171.8.123
    ports:
    - 9056:9050
    - 9057:9051
  node5:
    container_name: node5
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.98.156.3
    ports:
    - 9058:9050
    - 9059:9051
  node6:
    container_name: node6
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.135.11.134
    ports:
    - 9060:9050
    - 9061:9051
  node7:
    container_name: node7
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.141.149.215
    ports:
    - 9062:9050
    - 9063:9051
  node8:
    container_name: node8
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.54.114.181
    ports:
    - 9064:9050
    - 9065:9051
  node9:
    container_name: node9
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.150.242.146
    ports:
    - 9066:9050
    - 9067:9051
version: '3.8'
