networks:
  TOR_NETWORK:
    driver: nat
    ipam:
      config:
      - subnet: 192.168.2.0/24
services:
  node1:
    command:
    - entrypoint_crush.bat
    container_name: node1
    environment:
      NODE_IP: 192.168.2.54
      NODE_PORT: 9086
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.54
    platform: windows/amd64
    ports:
    - 9086:9050
    - 9066:9051
  node10:
    command:
    - entrypoint.bat
    container_name: node10
    environment:
      NODE_IP: 192.168.2.49
      NODE_PORT: 9081
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.49
    platform: windows/amd64
    ports:
    - 9081:9050
    - 9062:9051
  node2:
    command:
    - entrypoint.bat
    container_name: node2
    environment:
      NODE_IP: 192.168.2.167
      NODE_PORT: 9058
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.167
    platform: windows/amd64
    ports:
    - 9058:9050
    - 9054:9051
  node3:
    command:
    - entrypoint.bat
    container_name: node3
    environment:
      NODE_IP: 192.168.2.90
      NODE_PORT: 9083
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.90
    platform: windows/amd64
    ports:
    - 9083:9050
    - 9064:9051
  node4:
    command:
    - entrypoint.bat
    container_name: node4
    environment:
      NODE_IP: 192.168.2.245
      NODE_PORT: 9053
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.245
    platform: windows/amd64
    ports:
    - 9053:9050
    - 9079:9051
  node5:
    command:
    - entrypoint.bat
    container_name: node5
    environment:
      NODE_IP: 192.168.2.180
      NODE_PORT: 9056
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.180
    platform: windows/amd64
    ports:
    - 9056:9050
    - 9072:9051
  node6:
    command:
    - entrypoint.bat
    container_name: node6
    environment:
      NODE_IP: 192.168.2.140
      NODE_PORT: 9069
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.140
    platform: windows/amd64
    ports:
    - 9069:9050
    - 9085:9051
  node7:
    command:
    - entrypoint.bat
    container_name: node7
    environment:
      NODE_IP: 192.168.2.241
      NODE_PORT: 9090
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.241
    platform: windows/amd64
    ports:
    - 9090:9050
    - 9067:9051
  node8:
    command:
    - entrypoint.bat
    container_name: node8
    environment:
      NODE_IP: 192.168.2.211
      NODE_PORT: 9073
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.211
    platform: windows/amd64
    ports:
    - 9073:9050
    - 9094:9051
  node9:
    command:
    - entrypoint.bat
    container_name: node9
    environment:
      NODE_IP: 192.168.2.53
      NODE_PORT: 9100
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.53
    platform: windows/amd64
    ports:
    - 9100:9050
    - 9087:9051
