networks:
  TOR_NETWORK:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.1.0/24
services:
  node1:
    container_name: node1
    environment:
      NODE_IP: 192.168.1.128
      NODE_PORT: 9053
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.128
    platform: windows/amd64
    ports:
    - 9053:9050
    - 9079:9051
  node10:
    container_name: node10
    environment:
      NODE_IP: 192.168.1.149
      NODE_PORT: 9098
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.149
    platform: windows/amd64
    ports:
    - 9098:9050
    - 9080:9051
  node2:
    container_name: node2
    environment:
      NODE_IP: 192.168.1.175
      NODE_PORT: 9071
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.175
    platform: windows/amd64
    ports:
    - 9071:9050
    - 9078:9051
  node3:
    container_name: node3
    environment:
      NODE_IP: 192.168.1.216
      NODE_PORT: 9091
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.216
    platform: windows/amd64
    ports:
    - 9091:9050
    - 9090:9051
  node4:
    container_name: node4
    environment:
      NODE_IP: 192.168.1.81
      NODE_PORT: 9092
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.81
    platform: windows/amd64
    ports:
    - 9092:9050
    - 9077:9051
  node5:
    container_name: node5
    environment:
      NODE_IP: 192.168.1.155
      NODE_PORT: 9069
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.155
    platform: windows/amd64
    ports:
    - 9069:9050
    - 9100:9051
  node6:
    container_name: node6
    environment:
      NODE_IP: 192.168.1.126
      NODE_PORT: 9083
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.126
    platform: windows/amd64
    ports:
    - 9083:9050
    - 9094:9051
  node7:
    container_name: node7
    environment:
      NODE_IP: 192.168.1.156
      NODE_PORT: 9054
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.156
    platform: windows/amd64
    ports:
    - 9054:9050
    - 9061:9051
  node8:
    container_name: node8
    environment:
      NODE_IP: 192.168.1.110
      NODE_PORT: 9052
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.110
    platform: windows/amd64
    ports:
    - 9052:9050
    - 9060:9051
  node9:
    container_name: node9
    environment:
      NODE_IP: 192.168.1.35
      NODE_PORT: 9072
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.35
    platform: windows/amd64
    ports:
    - 9072:9050
    - 9067:9051
version: '3.8'
