networks:
  TOR_NETWORK:
    driver: nat
    ipam:
      config:
      - subnet: 192.168.1.0/24
services:
  node1:
    container_name: node1
    environment:
      NODE_IP: 192.168.1.2
      NODE_PORT: 9053
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.2
    platform: windows/amd64
    ports:
    - 9053:9050
    - 9089:9051
  node10:
    container_name: node10
    environment:
      NODE_IP: 192.168.1.146
      NODE_PORT: 9093
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.146
    platform: windows/amd64
    ports:
    - 9093:9050
    - 9088:9051
  node2:
    container_name: node2
    environment:
      NODE_IP: 192.168.1.60
      NODE_PORT: 9055
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.60
    platform: windows/amd64
    ports:
    - 9055:9050
    - 9098:9051
  node3:
    container_name: node3
    environment:
      NODE_IP: 192.168.1.52
      NODE_PORT: 9050
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.52
    platform: windows/amd64
    ports:
    - 9050:9050
    - 9075:9051
  node4:
    container_name: node4
    environment:
      NODE_IP: 192.168.1.208
      NODE_PORT: 9094
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.208
    platform: windows/amd64
    ports:
    - 9094:9050
    - 9097:9051
  node5:
    container_name: node5
    environment:
      NODE_IP: 192.168.1.54
      NODE_PORT: 9082
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.54
    platform: windows/amd64
    ports:
    - 9082:9050
    - 9073:9051
  node6:
    container_name: node6
    environment:
      NODE_IP: 192.168.1.157
      NODE_PORT: 9090
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.157
    platform: windows/amd64
    ports:
    - 9090:9050
    - 9071:9051
  node7:
    container_name: node7
    environment:
      NODE_IP: 192.168.1.130
      NODE_PORT: 9074
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.130
    platform: windows/amd64
    ports:
    - 9074:9050
    - 9060:9051
  node8:
    container_name: node8
    environment:
      NODE_IP: 192.168.1.86
      NODE_PORT: 9096
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.86
    platform: windows/amd64
    ports:
    - 9096:9050
    - 9067:9051
  node9:
    container_name: node9
    environment:
      NODE_IP: 192.168.1.28
      NODE_PORT: 9057
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.28
    platform: windows/amd64
    ports:
    - 9057:9050
    - 9078:9051
