networks:
  TOR_NETWORK:
    driver: nat
    ipam:
      config:
      - subnet: 192.168.2.0/24
services:
  node1:
    command:
    - entrypoint.bat
    container_name: node1
    dns:
    - 8.8.8.8
    environment:
      NODE_IP: 192.168.2.26
      NODE_PORT: 9050
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.26
    platform: windows/amd64
    ports:
    - 9053:9050
    - 9068:9051
  node10:
    command:
    - entrypoint.bat
    container_name: node10
    dns:
    - 8.8.8.8
    environment:
      NODE_IP: 192.168.2.134
      NODE_PORT: 9075
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.134
    platform: windows/amd64
    ports:
    - 9075:9050
    - 9092:9051
  node2:
    command:
    - entrypoint.bat
    container_name: node2
    dns:
    - 8.8.8.8
    environment:
      NODE_IP: 192.168.2.43
      NODE_PORT: 9083
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.43
    platform: windows/amd64
    ports:
    - 9083:9050
    - 9095:9051
  node3:
    command:
    - entrypoint.bat
    container_name: node3
    dns:
    - 8.8.8.8
    environment:
      NODE_IP: 192.168.2.39
      NODE_PORT: 9050
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.39
    platform: windows/amd64
    ports:
    - 9069:9050
    - 9094:9051
  node4:
    command:
    - entrypoint.bat
    container_name: node4
    dns:
    - 8.8.8.8
    environment:
      NODE_IP: 192.168.2.239
      NODE_PORT: 9073
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.239
    platform: windows/amd64
    ports:
    - 9073:9050
    - 9080:9051
  node5:
    command:
    - entrypoint.bat
    container_name: node5
    dns:
    - 8.8.8.8
    environment:
      NODE_IP: 192.168.2.246
      NODE_PORT: 9081
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.246
    platform: windows/amd64
    ports:
    - 9081:9050
    - 9066:9051
  node6:
    command:
    - entrypoint.bat
    container_name: node6
    dns:
    - 8.8.8.8
    environment:
      NODE_IP: 192.168.2.252
      NODE_PORT: 9097
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.252
    platform: windows/amd64
    ports:
    - 9097:9050
    - 9057:9051
  node7:
    command:
    - entrypoint.bat
    container_name: node7
    dns:
    - 8.8.8.8
    environment:
      NODE_IP: 192.168.2.100
      NODE_PORT: 9093
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.100
    platform: windows/amd64
    ports:
    - 9093:9050
    - 9084:9051
  node8:
    command:
    - entrypoint.bat
    container_name: node8
    dns:
    - 8.8.8.8
    environment:
      NODE_IP: 192.168.2.97
      NODE_PORT: 9088
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.97
    platform: windows/amd64
    ports:
    - 9088:9050
    - 9076:9051
  node9:
    command:
    - entrypoint.bat
    container_name: node9
    dns:
    - 8.8.8.8
    environment:
      NODE_IP: 192.168.2.25
      NODE_PORT: 9059
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.25
    platform: windows/amd64
    ports:
    - 9059:9050
    - 9054:9051
