networks:
  TOR_NETWORK:
    driver: nat
    ipam:
      config:
      - subnet: 192.168.1.0/24
services:
  node1:
    container_name: node1
    environment:
      NODE_IP: 192.168.1.107
      NODE_PORT: 9076
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.107
    platform: windows/amd64
    ports:
    - 9076:9050
    - 9061:9051
  node10:
    container_name: node10
    environment:
      NODE_IP: 192.168.1.66
      NODE_PORT: 9056
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.66
    platform: windows/amd64
    ports:
    - 9056:9050
    - 9093:9051
  node2:
    container_name: node2
    environment:
      NODE_IP: 192.168.1.14
      NODE_PORT: 9065
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.14
    platform: windows/amd64
    ports:
    - 9065:9050
    - 9094:9051
  node3:
    container_name: node3
    environment:
      NODE_IP: 192.168.1.230
      NODE_PORT: 9097
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.230
    platform: windows/amd64
    ports:
    - 9097:9050
    - 9078:9051
  node4:
    container_name: node4
    environment:
      NODE_IP: 192.168.1.141
      NODE_PORT: 9073
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.141
    platform: windows/amd64
    ports:
    - 9073:9050
    - 9074:9051
  node5:
    container_name: node5
    environment:
      NODE_IP: 192.168.1.243
      NODE_PORT: 9092
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.243
    platform: windows/amd64
    ports:
    - 9092:9050
    - 9058:9051
  node6:
    container_name: node6
    environment:
      NODE_IP: 192.168.1.227
      NODE_PORT: 9080
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.227
    platform: windows/amd64
    ports:
    - 9080:9050
    - 9052:9051
  node7:
    container_name: node7
    environment:
      NODE_IP: 192.168.1.169
      NODE_PORT: 9053
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.169
    platform: windows/amd64
    ports:
    - 9053:9050
    - 9089:9051
  node8:
    container_name: node8
    environment:
      NODE_IP: 192.168.1.48
      NODE_PORT: 9081
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.48
    platform: windows/amd64
    ports:
    - 9081:9050
    - 9086:9051
  node9:
    container_name: node9
    environment:
      NODE_IP: 192.168.1.118
      NODE_PORT: 9072
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.118
    platform: windows/amd64
    ports:
    - 9072:9050
    - 9064:9051
