networks:
  TOR_NETWORK:
    driver: bridge
    ipam:
      config:
      - subnet: 192.0.0.0/8
services:
  node1:
    container_name: node1
    environment:
      NODE_IP: 192.204.106.102
      NODE_PORT: 9088
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.204.106.102
    ports:
    - 9088:9050
    - 9090:9051
  node10:
    container_name: node10
    environment:
      NODE_IP: 192.147.27.42
      NODE_PORT: 9077
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.147.27.42
    ports:
    - 9077:9050
    - 9095:9051
  node2:
    container_name: node2
    environment:
      NODE_IP: 192.246.58.94
      NODE_PORT: 9073
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.246.58.94
    ports:
    - 9073:9050
    - 9075:9051
  node3:
    container_name: node3
    environment:
      NODE_IP: 192.5.175.236
      NODE_PORT: 9094
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.5.175.236
    ports:
    - 9094:9050
    - 9098:9051
  node4:
    container_name: node4
    environment:
      NODE_IP: 192.147.223.159
      NODE_PORT: 9076
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.147.223.159
    ports:
    - 9076:9050
    - 9093:9051
  node5:
    container_name: node5
    environment:
      NODE_IP: 192.147.35.238
      NODE_PORT: 9064
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.147.35.238
    ports:
    - 9064:9050
    - 9068:9051
  node6:
    container_name: node6
    environment:
      NODE_IP: 192.213.66.39
      NODE_PORT: 9053
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.213.66.39
    ports:
    - 9053:9050
    - 9069:9051
  node7:
    container_name: node7
    environment:
      NODE_IP: 192.4.229.91
      NODE_PORT: 9060
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.4.229.91
    ports:
    - 9060:9050
    - 9054:9051
  node8:
    container_name: node8
    environment:
      NODE_IP: 192.111.177.78
      NODE_PORT: 9062
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.111.177.78
    ports:
    - 9062:9050
    - 9067:9051
  node9:
    container_name: node9
    environment:
      NODE_IP: 192.136.83.149
      NODE_PORT: 9071
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.136.83.149
    ports:
    - 9071:9050
    - 9078:9051
version: '3.8'
