networks:
  TOR_NETWORK:
    driver: nat
    ipam:
      config:
      - subnet: 192.168.1.0/24
services:
  node1:
    container_name: node1
    environment:
      NODE_IP: 192.168.1.133
      NODE_PORT: 9095
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.133
    platform: windows/amd64
    ports:
    - 9095:9050
    - 9069:9051
  node10:
    container_name: node10
    environment:
      NODE_IP: 192.168.1.197
      NODE_PORT: 9085
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.197
    platform: windows/amd64
    ports:
    - 9085:9050
    - 9078:9051
  node2:
    container_name: node2
    environment:
      NODE_IP: 192.168.1.138
      NODE_PORT: 9054
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.138
    platform: windows/amd64
    ports:
    - 9054:9050
    - 9074:9051
  node3:
    container_name: node3
    environment:
      NODE_IP: 192.168.1.42
      NODE_PORT: 9061
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.42
    platform: windows/amd64
    ports:
    - 9061:9050
    - 9077:9051
  node4:
    container_name: node4
    environment:
      NODE_IP: 192.168.1.104
      NODE_PORT: 9063
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.104
    platform: windows/amd64
    ports:
    - 9063:9050
    - 9073:9051
  node5:
    container_name: node5
    environment:
      NODE_IP: 192.168.1.207
      NODE_PORT: 9058
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.207
    platform: windows/amd64
    ports:
    - 9058:9050
    - 9081:9051
  node6:
    container_name: node6
    environment:
      NODE_IP: 192.168.1.172
      NODE_PORT: 9080
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.172
    platform: windows/amd64
    ports:
    - 9080:9050
    - 9090:9051
  node7:
    container_name: node7
    environment:
      NODE_IP: 192.168.1.92
      NODE_PORT: 9079
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.92
    platform: windows/amd64
    ports:
    - 9079:9050
    - 9091:9051
  node8:
    container_name: node8
    environment:
      NODE_IP: 192.168.1.47
      NODE_PORT: 9055
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.47
    platform: windows/amd64
    ports:
    - 9055:9050
    - 9092:9051
  node9:
    container_name: node9
    environment:
      NODE_IP: 192.168.1.173
      NODE_PORT: 9087
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.173
    platform: windows/amd64
    ports:
    - 9087:9050
    - 9072:9051
