networks:
  TOR_NETWORK:
    driver: nat
    ipam:
      config:
      - subnet: 192.168.2.0/24
services:
  node1:
    command:
    - entrypoint.bat
    container_name: node1
    environment:
      NODE_IP: 192.168.2.76
      NODE_PORT: 9050
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.76
    platform: windows/amd64
    ports:
    - 9056:9050
    - 9055:9051
  node10:
    command:
    - entrypoint.bat
    container_name: node10
    environment:
      NODE_IP: 192.168.2.134
      NODE_PORT: 9064
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.134
    platform: windows/amd64
    ports:
    - 9064:9050
    - 9090:9051
  node2:
    command:
    - entrypoint.bat
    container_name: node2
    environment:
      NODE_IP: 192.168.2.208
      NODE_PORT: 9077
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.208
    platform: windows/amd64
    ports:
    - 9077:9050
    - 9073:9051
  node3:
    command:
    - entrypoint.bat
    container_name: node3
    environment:
      NODE_IP: 192.168.2.213
      NODE_PORT: 9089
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.213
    platform: windows/amd64
    ports:
    - 9089:9050
    - 9094:9051
  node4:
    command:
    - entrypoint.bat
    container_name: node4
    environment:
      NODE_IP: 192.168.2.69
      NODE_PORT: 9099
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.69
    platform: windows/amd64
    ports:
    - 9099:9050
    - 9081:9051
  node5:
    command:
    - entrypoint.bat
    container_name: node5
    environment:
      NODE_IP: 192.168.2.217
      NODE_PORT: 9095
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.217
    platform: windows/amd64
    ports:
    - 9095:9050
    - 9083:9051
  node6:
    command:
    - entrypoint.bat
    container_name: node6
    environment:
      NODE_IP: 192.168.2.98
      NODE_PORT: 9080
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.98
    platform: windows/amd64
    ports:
    - 9080:9050
    - 9088:9051
  node7:
    command:
    - entrypoint.bat
    container_name: node7
    environment:
      NODE_IP: 192.168.2.81
      NODE_PORT: 9066
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.81
    platform: windows/amd64
    ports:
    - 9066:9050
    - 9079:9051
  node8:
    command:
    - entrypoint.bat
    container_name: node8
    environment:
      NODE_IP: 192.168.2.169
      NODE_PORT: 9082
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.169
    platform: windows/amd64
    ports:
    - 9082:9050
    - 9061:9051
  node9:
    command:
    - entrypoint.bat
    container_name: node9
    environment:
      NODE_IP: 192.168.2.204
      NODE_PORT: 9074
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.204
    platform: windows/amd64
    ports:
    - 9074:9050
    - 9059:9051
