networks:
  TOR_NETWORK:
    driver: nat
    ipam:
      config:
      - subnet: 192.168.1.0/24
services:
  node1:
    container_name: node1
    entrypoint:
    - cmd
    - /c
    - C:\app\entrypoint.bat
    environment:
      NODE_IP: 192.168.1.22
      NODE_PORT: 9087
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.22
    platform: windows/amd64
    ports:
    - 9087:9050
    - 9051:9051
  node10:
    container_name: node10
    entrypoint:
    - cmd
    - /c
    - C:\app\entrypoint.bat
    environment:
      NODE_IP: 192.168.1.121
      NODE_PORT: 9050
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.121
    platform: windows/amd64
    ports:
    - 9050:9050
    - 9090:9051
  node2:
    container_name: node2
    entrypoint:
    - cmd
    - /c
    - C:\app\entrypoint.bat
    environment:
      NODE_IP: 192.168.1.4
      NODE_PORT: 9055
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.4
    platform: windows/amd64
    ports:
    - 9055:9050
    - 9070:9051
  node3:
    container_name: node3
    entrypoint:
    - cmd
    - /c
    - C:\app\entrypoint.bat
    environment:
      NODE_IP: 192.168.1.83
      NODE_PORT: 9079
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.83
    platform: windows/amd64
    ports:
    - 9079:9050
    - 9061:9051
  node4:
    container_name: node4
    entrypoint:
    - cmd
    - /c
    - C:\app\entrypoint.bat
    environment:
      NODE_IP: 192.168.1.235
      NODE_PORT: 9078
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.235
    platform: windows/amd64
    ports:
    - 9078:9050
    - 9092:9051
  node5:
    container_name: node5
    entrypoint:
    - cmd
    - /c
    - C:\app\entrypoint.bat
    environment:
      NODE_IP: 192.168.1.155
      NODE_PORT: 9056
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.155
    platform: windows/amd64
    ports:
    - 9056:9050
    - 9088:9051
  node6:
    container_name: node6
    entrypoint:
    - cmd
    - /c
    - C:\app\entrypoint.bat
    environment:
      NODE_IP: 192.168.1.122
      NODE_PORT: 9057
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.122
    platform: windows/amd64
    ports:
    - 9057:9050
    - 9075:9051
  node7:
    container_name: node7
    entrypoint:
    - cmd
    - /c
    - C:\app\entrypoint.bat
    environment:
      NODE_IP: 192.168.1.151
      NODE_PORT: 9054
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.151
    platform: windows/amd64
    ports:
    - 9054:9050
    - 9082:9051
  node8:
    container_name: node8
    entrypoint:
    - cmd
    - /c
    - C:\app\entrypoint.bat
    environment:
      NODE_IP: 192.168.1.166
      NODE_PORT: 9059
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.166
    platform: windows/amd64
    ports:
    - 9059:9050
    - 9098:9051
  node9:
    container_name: node9
    entrypoint:
    - cmd
    - /c
    - C:\app\entrypoint.bat
    environment:
      NODE_IP: 192.168.1.244
      NODE_PORT: 9069
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.244
    platform: windows/amd64
    ports:
    - 9069:9050
    - 9100:9051
