networks:
  TOR_NETWORK:
    driver: nat
    ipam:
      config:
      - subnet: 192.168.2.0/24
services:
  node1:
    command:
    - entrypoint.bat
    container_name: node1
    environment:
      NODE_IP: 192.168.2.4
      NODE_PORT: 9078
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.4
    platform: windows/amd64
    ports:
    - 9078:9050
    - 9081:9051
  node10:
    command:
    - entrypoint.bat
    container_name: node10
    environment:
      NODE_IP: 192.168.2.84
      NODE_PORT: 9057
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.84
    platform: windows/amd64
    ports:
    - 9057:9050
    - 9056:9051
  node2:
    command:
    - entrypoint.bat
    container_name: node2
    environment:
      NODE_IP: 192.168.2.252
      NODE_PORT: 9099
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.252
    platform: windows/amd64
    ports:
    - 9099:9050
    - 9069:9051
  node3:
    command:
    - entrypoint.bat
    container_name: node3
    environment:
      NODE_IP: 192.168.2.134
      NODE_PORT: 9063
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.134
    platform: windows/amd64
    ports:
    - 9063:9050
    - 9052:9051
  node4:
    command:
    - entrypoint.bat
    container_name: node4
    environment:
      NODE_IP: 192.168.2.199
      NODE_PORT: 9096
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.199
    platform: windows/amd64
    ports:
    - 9096:9050
    - 9070:9051
  node5:
    command:
    - entrypoint.bat
    container_name: node5
    environment:
      NODE_IP: 192.168.2.188
      NODE_PORT: 9097
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.188
    platform: windows/amd64
    ports:
    - 9097:9050
    - 9084:9051
  node6:
    command:
    - entrypoint.bat
    container_name: node6
    environment:
      NODE_IP: 192.168.2.65
      NODE_PORT: 9090
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.65
    platform: windows/amd64
    ports:
    - 9090:9050
    - 9091:9051
  node7:
    command:
    - entrypoint.bat
    container_name: node7
    environment:
      NODE_IP: 192.168.2.26
      NODE_PORT: 9092
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.26
    platform: windows/amd64
    ports:
    - 9092:9050
    - 9053:9051
  node8:
    command:
    - entrypoint.bat
    container_name: node8
    environment:
      NODE_IP: 192.168.2.123
      NODE_PORT: 9085
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.123
    platform: windows/amd64
    ports:
    - 9085:9050
    - 9077:9051
  node9:
    command:
    - entrypoint.bat
    container_name: node9
    environment:
      NODE_IP: 192.168.2.202
      NODE_PORT: 9064
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.202
    platform: windows/amd64
    ports:
    - 9064:9050
    - 9076:9051
