networks:
  TOR_NETWORK:
    driver: nat
    ipam:
      config:
      - subnet: 192.168.2.0/24
services:
  node1:
    command:
    - entrypoint.bat
    container_name: node1
    dns:
    - 8.8.8.8
    environment:
      NODE_IP: 192.168.2.82
      NODE_PORT: 9050
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.82
    platform: windows/amd64
    ports:
    - 9063:9050
    - 9077:9051
  node10:
    command:
    - entrypoint.bat
    container_name: node10
    dns:
    - 8.8.8.8
    environment:
      NODE_IP: 192.168.2.93
      NODE_PORT: 9079
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.93
    platform: windows/amd64
    ports:
    - 9079:9050
    - 9069:9051
  node2:
    command:
    - entrypoint.bat
    container_name: node2
    dns:
    - 8.8.8.8
    environment:
      NODE_IP: 192.168.2.208
      NODE_PORT: 9097
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.208
    platform: windows/amd64
    ports:
    - 9097:9050
    - 9071:9051
  node3:
    command:
    - entrypoint.bat
    container_name: node3
    dns:
    - 8.8.8.8
    environment:
      NODE_IP: 192.168.2.126
      NODE_PORT: 9050
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.126
    platform: windows/amd64
    ports:
    - 9053:9050
    - 9076:9051
  node4:
    command:
    - entrypoint.bat
    container_name: node4
    dns:
    - 8.8.8.8
    environment:
      NODE_IP: 192.168.2.80
      NODE_PORT: 9090
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.80
    platform: windows/amd64
    ports:
    - 9090:9050
    - 9051:9051
  node5:
    command:
    - entrypoint.bat
    container_name: node5
    dns:
    - 8.8.8.8
    environment:
      NODE_IP: 192.168.2.55
      NODE_PORT: 9096
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.55
    platform: windows/amd64
    ports:
    - 9096:9050
    - 9093:9051
  node6:
    command:
    - entrypoint.bat
    container_name: node6
    dns:
    - 8.8.8.8
    environment:
      NODE_IP: 192.168.2.226
      NODE_PORT: 9086
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.226
    platform: windows/amd64
    ports:
    - 9086:9050
    - 9072:9051
  node7:
    command:
    - entrypoint.bat
    container_name: node7
    dns:
    - 8.8.8.8
    environment:
      NODE_IP: 192.168.2.68
      NODE_PORT: 9068
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.68
    platform: windows/amd64
    ports:
    - 9068:9050
    - 9084:9051
  node8:
    command:
    - entrypoint.bat
    container_name: node8
    dns:
    - 8.8.8.8
    environment:
      NODE_IP: 192.168.2.27
      NODE_PORT: 9062
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.27
    platform: windows/amd64
    ports:
    - 9062:9050
    - 9080:9051
  node9:
    command:
    - entrypoint.bat
    container_name: node9
    dns:
    - 8.8.8.8
    environment:
      NODE_IP: 192.168.2.215
      NODE_PORT: 9085
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.215
    platform: windows/amd64
    ports:
    - 9085:9050
    - 9056:9051
