networks:
  TOR_NETWORK:
    driver: bridge
    ipam:
      config:
      - subnet: 192.0.0.0/8
services:
  node1:
    container_name: node1
    environment:
      NODE_PORT: 9065
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.48.181.135
    ports:
    - 9065:9050
    - 9071:9051
  node10:
    container_name: node10
    environment:
      NODE_PORT: 9072
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.19.166.76
    ports:
    - 9072:9050
    - 9060:9051
  node2:
    container_name: node2
    environment:
      NODE_PORT: 9081
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.150.177.142
    ports:
    - 9081:9050
    - 9076:9051
  node3:
    container_name: node3
    environment:
      NODE_PORT: 9087
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.246.210.49
    ports:
    - 9087:9050
    - 9086:9051
  node4:
    container_name: node4
    environment:
      NODE_PORT: 9051
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.91.200.219
    ports:
    - 9051:9050
    - 9057:9051
  node5:
    container_name: node5
    environment:
      NODE_PORT: 9089
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.207.33.195
    ports:
    - 9089:9050
    - 9077:9051
  node6:
    container_name: node6
    environment:
      NODE_PORT: 9054
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.247.146.251
    ports:
    - 9054:9050
    - 9070:9051
  node7:
    container_name: node7
    environment:
      NODE_PORT: 9099
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.52.126.238
    ports:
    - 9099:9050
    - 9092:9051
  node8:
    container_name: node8
    environment:
      NODE_PORT: 9068
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.141.164.182
    ports:
    - 9068:9050
    - 9080:9051
  node9:
    container_name: node9
    environment:
      NODE_PORT: 9067
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.10.173.45
    ports:
    - 9067:9050
    - 9073:9051
version: '3.8'
