networks:
  TOR_NETWORK:
    driver: nat
    ipam:
      config:
      - subnet: 192.168.1.0/24
services:
  node1:
    container_name: node1
    environment:
      NODE_IP: 192.168.1.123
      NODE_PORT: 9061
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.123
    platform: windows/amd64
    ports:
    - 9061:9050
    - 9066:9051
  node10:
    container_name: node10
    environment:
      NODE_IP: 192.168.1.130
      NODE_PORT: 9086
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.130
    platform: windows/amd64
    ports:
    - 9086:9050
    - 9080:9051
  node2:
    container_name: node2
    environment:
      NODE_IP: 192.168.1.92
      NODE_PORT: 9082
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.92
    platform: windows/amd64
    ports:
    - 9082:9050
    - 9087:9051
  node3:
    container_name: node3
    environment:
      NODE_IP: 192.168.1.28
      NODE_PORT: 9081
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.28
    platform: windows/amd64
    ports:
    - 9081:9050
    - 9063:9051
  node4:
    container_name: node4
    environment:
      NODE_IP: 192.168.1.237
      NODE_PORT: 9069
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.237
    platform: windows/amd64
    ports:
    - 9069:9050
    - 9084:9051
  node5:
    container_name: node5
    environment:
      NODE_IP: 192.168.1.62
      NODE_PORT: 9051
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.62
    platform: windows/amd64
    ports:
    - 9051:9050
    - 9076:9051
  node6:
    container_name: node6
    environment:
      NODE_IP: 192.168.1.58
      NODE_PORT: 9099
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.58
    platform: windows/amd64
    ports:
    - 9099:9050
    - 9077:9051
  node7:
    container_name: node7
    environment:
      NODE_IP: 192.168.1.88
      NODE_PORT: 9067
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.88
    platform: windows/amd64
    ports:
    - 9067:9050
    - 9088:9051
  node8:
    container_name: node8
    environment:
      NODE_IP: 192.168.1.133
      NODE_PORT: 9093
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.133
    platform: windows/amd64
    ports:
    - 9093:9050
    - 9062:9051
  node9:
    container_name: node9
    environment:
      NODE_IP: 192.168.1.230
      NODE_PORT: 9089
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.230
    platform: windows/amd64
    ports:
    - 9089:9050
    - 9065:9051
