networks:
  TOR_NETWORK:
    driver: nat
    ipam:
      config:
      - subnet: 192.168.2.0/24
services:
  node1:
    command:
    - entrypoint_crush.bat
    container_name: node1
    environment:
      NODE_IP: 192.168.2.242
      NODE_PORT: 9050
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.242
    platform: windows/amd64
    ports:
    - 9099:9050
    - 9097:9051
  node10:
    command:
    - entrypoint.bat
    container_name: node10
    environment:
      NODE_IP: 192.168.2.126
      NODE_PORT: 9081
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.126
    platform: windows/amd64
    ports:
    - 9081:9050
    - 9074:9051
  node2:
    command:
    - entrypoint.bat
    container_name: node2
    environment:
      NODE_IP: 192.168.2.237
      NODE_PORT: 9067
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.237
    platform: windows/amd64
    ports:
    - 9067:9050
    - 9078:9051
  node3:
    command:
    - entrypoint.bat
    container_name: node3
    environment:
      NODE_IP: 192.168.2.121
      NODE_PORT: 9065
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.121
    platform: windows/amd64
    ports:
    - 9065:9050
    - 9075:9051
  node4:
    command:
    - entrypoint.bat
    container_name: node4
    environment:
      NODE_IP: 192.168.2.12
      NODE_PORT: 9062
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.12
    platform: windows/amd64
    ports:
    - 9062:9050
    - 9071:9051
  node5:
    command:
    - entrypoint.bat
    container_name: node5
    environment:
      NODE_IP: 192.168.2.214
      NODE_PORT: 9083
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.214
    platform: windows/amd64
    ports:
    - 9083:9050
    - 9088:9051
  node6:
    command:
    - entrypoint.bat
    container_name: node6
    environment:
      NODE_IP: 192.168.2.132
      NODE_PORT: 9053
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.132
    platform: windows/amd64
    ports:
    - 9053:9050
    - 9080:9051
  node7:
    command:
    - entrypoint.bat
    container_name: node7
    environment:
      NODE_IP: 192.168.2.227
      NODE_PORT: 9057
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.227
    platform: windows/amd64
    ports:
    - 9057:9050
    - 9059:9051
  node8:
    command:
    - entrypoint.bat
    container_name: node8
    environment:
      NODE_IP: 192.168.2.107
      NODE_PORT: 9068
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.107
    platform: windows/amd64
    ports:
    - 9068:9050
    - 9070:9051
  node9:
    command:
    - entrypoint.bat
    container_name: node9
    environment:
      NODE_IP: 192.168.2.74
      NODE_PORT: 9086
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.74
    platform: windows/amd64
    ports:
    - 9086:9050
    - 9091:9051
