networks:
  TOR_NETWORK:
    driver: nat
    ipam:
      config:
      - subnet: 192.168.2.0/24
services:
  node1:
    command:
    - entrypoint.bat
    container_name: node1
    environment:
      NODE_IP: 192.168.2.115
      NODE_PORT: 9050
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.115
    platform: windows/amd64
    ports:
    - 9075:9050
    - 9064:9051
  node10:
    command:
    - entrypoint.bat
    container_name: node10
    environment:
      NODE_IP: 192.168.2.123
      NODE_PORT: 9090
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.123
    platform: windows/amd64
    ports:
    - 9090:9050
    - 9068:9051
  node2:
    command:
    - entrypoint_crush.bat 
    container_name: node2
    environment:
      NODE_IP: 192.168.2.217
      NODE_PORT: 9080
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.217
    platform: windows/amd64
    ports:
    - 9080:9050
    - 9077:9051
  node3:
    command:
    - entrypoint.bat
    container_name: node3
    environment:
      NODE_IP: 192.168.2.196
      NODE_PORT: 9050
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.196
    platform: windows/amd64
    ports:
    - 9088:9050
    - 9051:9051
  node4:
    command:
    - entrypoint.bat
    container_name: node4
    environment:
      NODE_IP: 192.168.2.158
      NODE_PORT: 9086
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.158
    platform: windows/amd64
    ports:
    - 9086:9050
    - 9084:9051
  node5:
    command:
    - entrypoint.bat
    container_name: node5
    environment:
      NODE_IP: 192.168.2.160
      NODE_PORT: 9092
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.160
    platform: windows/amd64
    ports:
    - 9092:9050
    - 9095:9051
  node6:
    command:
    - entrypoint.bat
    container_name: node6
    environment:
      NODE_IP: 192.168.2.113
      NODE_PORT: 9076
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.113
    platform: windows/amd64
    ports:
    - 9076:9050
    - 9057:9051
  node7:
    command:
    - entrypoint.bat
    container_name: node7
    environment:
      NODE_IP: 192.168.2.84
      NODE_PORT: 9082
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.84
    platform: windows/amd64
    ports:
    - 9082:9050
    - 9091:9051
  node8:
    command:
    - entrypoint.bat
    container_name: node8
    environment:
      NODE_IP: 192.168.2.110
      NODE_PORT: 9070
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.110
    platform: windows/amd64
    ports:
    - 9070:9050
    - 9073:9051
  node9:
    command:
    - entrypoint.bat
    container_name: node9
    environment:
      NODE_IP: 192.168.2.3
      NODE_PORT: 9085
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.3
    platform: windows/amd64
    ports:
    - 9085:9050
    - 9100:9051
