networks:
  TOR_NETWORK:
    driver: nat
    ipam:
      config:
      - subnet: 192.168.1.0/24
services:
  node1:
    container_name: node1
    environment:
      NODE_IP: 192.168.1.56
      NODE_PORT: 9097
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.56
    platform: windows/amd64
    ports:
    - 9097:9050
    - 9094:9051
  node10:
    container_name: node10
    environment:
      NODE_IP: 192.168.1.197
      NODE_PORT: 9082
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.197
    platform: windows/amd64
    ports:
    - 9082:9050
    - 9085:9051
  node2:
    container_name: node2
    environment:
      NODE_IP: 192.168.1.112
      NODE_PORT: 9091
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.112
    platform: windows/amd64
    ports:
    - 9091:9050
    - 9056:9051
  node3:
    container_name: node3
    environment:
      NODE_IP: 192.168.1.33
      NODE_PORT: 9075
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.33
    platform: windows/amd64
    ports:
    - 9075:9050
    - 9079:9051
  node4:
    container_name: node4
    environment:
      NODE_IP: 192.168.1.120
      NODE_PORT: 9080
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.120
    platform: windows/amd64
    ports:
    - 9080:9050
    - 9070:9051
  node5:
    container_name: node5
    environment:
      NODE_IP: 192.168.1.148
      NODE_PORT: 9067
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.148
    platform: windows/amd64
    ports:
    - 9067:9050
    - 9052:9051
  node6:
    container_name: node6
    environment:
      NODE_IP: 192.168.1.14
      NODE_PORT: 9086
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.14
    platform: windows/amd64
    ports:
    - 9086:9050
    - 9092:9051
  node7:
    container_name: node7
    environment:
      NODE_IP: 192.168.1.150
      NODE_PORT: 9050
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.150
    platform: windows/amd64
    ports:
    - 9050:9050
    - 9074:9051
  node8:
    container_name: node8
    environment:
      NODE_IP: 192.168.1.44
      NODE_PORT: 9057
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.44
    platform: windows/amd64
    ports:
    - 9057:9050
    - 9072:9051
  node9:
    container_name: node9
    environment:
      NODE_IP: 192.168.1.170
      NODE_PORT: 9090
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.1.170
    platform: windows/amd64
    ports:
    - 9090:9050
    - 9060:9051
