networks:
  TOR_NETWORK:
    driver: nat
    ipam:
      config:
      - subnet: 192.168.2.0/24
services:
  node1:
    command:
    - entrypoint.bat
    container_name: node1
    environment:
      NODE_IP: 192.168.2.5
      NODE_PORT: 9060
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.5
    platform: windows/amd64
    ports:
    - 9060:9050
    - 9075:9051
  node10:
    command:
    - entrypoint.bat
    container_name: node10
    environment:
      NODE_IP: 192.168.2.75
      NODE_PORT: 9086
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.75
    platform: windows/amd64
    ports:
    - 9086:9050
    - 9088:9051
  node2:
    command:
    - entrypoint.bat
    container_name: node2
    environment:
      NODE_IP: 192.168.2.98
      NODE_PORT: 9087
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.98
    platform: windows/amd64
    ports:
    - 9087:9050
    - 9094:9051
  node3:
    command:
    - entrypoint.bat
    container_name: node3
    environment:
      NODE_IP: 192.168.2.9
      NODE_PORT: 9093
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.9
    platform: windows/amd64
    ports:
    - 9093:9050
    - 9057:9051
  node4:
    command:
    - entrypoint.bat
    container_name: node4
    environment:
      NODE_IP: 192.168.2.209
      NODE_PORT: 9099
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.209
    platform: windows/amd64
    ports:
    - 9099:9050
    - 9078:9051
  node5:
    command:
    - entrypoint.bat
    container_name: node5
    environment:
      NODE_IP: 192.168.2.76
      NODE_PORT: 9055
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.76
    platform: windows/amd64
    ports:
    - 9055:9050
    - 9059:9051
  node6:
    command:
    - entrypoint.bat
    container_name: node6
    environment:
      NODE_IP: 192.168.2.78
      NODE_PORT: 9089
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.78
    platform: windows/amd64
    ports:
    - 9089:9050
    - 9053:9051
  node7:
    command:
    - entrypoint.bat
    container_name: node7
    environment:
      NODE_IP: 192.168.2.178
      NODE_PORT: 9065
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.178
    platform: windows/amd64
    ports:
    - 9065:9050
    - 9068:9051
  node8:
    command:
    - entrypoint.bat
    container_name: node8
    environment:
      NODE_IP: 192.168.2.2
      NODE_PORT: 9067
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.2
    platform: windows/amd64
    ports:
    - 9067:9050
    - 9056:9051
  node9:
    command:
    - entrypoint.bat
    container_name: node9
    environment:
      NODE_IP: 192.168.2.111
      NODE_PORT: 9076
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.111
    platform: windows/amd64
    ports:
    - 9076:9050
    - 9096:9051
