networks:
  TOR_NETWORK:
    driver: bridge
    ipam:
      config:
      - subnet: 192.0.0.0/8
services:
  node1:
    container_name: node1
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.128.170.58
    ports:
    - 9050:9050
    - 9051:9051
  node10:
    container_name: node10
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.114.63.8
    ports:
    - 9068:9050
    - 9069:9051
  node2:
    container_name: node2
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.237.211.196
    ports:
    - 9052:9050
    - 9053:9051
  node3:
    container_name: node3
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.14.214.88
    ports:
    - 9054:9050
    - 9055:9051
  node4:
    container_name: node4
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.8.251.138
    ports:
    - 9056:9050
    - 9057:9051
  node5:
    container_name: node5
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.71.236.148
    ports:
    - 9058:9050
    - 9059:9051
  node6:
    container_name: node6
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.167.109.116
    ports:
    - 9060:9050
    - 9061:9051
  node7:
    container_name: node7
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.254.121.102
    ports:
    - 9062:9050
    - 9063:9051
  node8:
    container_name: node8
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.36.11.193
    ports:
    - 9064:9050
    - 9065:9051
  node9:
    container_name: node9
    image: eclipse/cpp_gcc
    networks:
      TOR_NETWORK:
        ipv4_address: 192.40.73.250
    ports:
    - 9066:9050
    - 9067:9051
version: '3.8'
