networks:
  TOR_NETWORK:
    driver: nat
    ipam:
      config:
      - subnet: 192.168.2.0/24
services:
  node1:
    command:
    - entrypoint.bat
    container_name: node1
    environment:
      NODE_IP: 192.168.2.113
      NODE_PORT: 9050
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.113
    platform: windows/amd64
    ports:
    - 9081:9050
    - 9079:9051
  node10:
    command:
    - entrypoint.bat
    container_name: node10
    environment:
      NODE_IP: 192.168.2.110
      NODE_PORT: 9086
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.110
    platform: windows/amd64
    ports:
    - 9086:9050
    - 9053:9051
  node2:
    command:
    - entrypoint.bat
    container_name: node2
    environment:
      NODE_IP: 192.168.2.76
      NODE_PORT: 9085
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.76
    platform: windows/amd64
    ports:
    - 9085:9050
    - 9059:9051
  node3:
    command:
    - entrypoint.bat
    container_name: node3
    environment:
      NODE_IP: 192.168.2.120
      NODE_PORT: 9065
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.120
    platform: windows/amd64
    ports:
    - 9065:9050
    - 9100:9051
  node4:
    command:
    - entrypoint.bat
    container_name: node4
    environment:
      NODE_IP: 192.168.2.128
      NODE_PORT: 9072
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.128
    platform: windows/amd64
    ports:
    - 9072:9050
    - 9077:9051
  node5:
    command:
    - entrypoint.bat
    container_name: node5
    environment:
      NODE_IP: 192.168.2.122
      NODE_PORT: 9082
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.122
    platform: windows/amd64
    ports:
    - 9082:9050
    - 9078:9051
  node6:
    command:
    - entrypoint.bat
    container_name: node6
    environment:
      NODE_IP: 192.168.2.178
      NODE_PORT: 9064
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.178
    platform: windows/amd64
    ports:
    - 9064:9050
    - 9088:9051
  node7:
    command:
    - entrypoint.bat
    container_name: node7
    environment:
      NODE_IP: 192.168.2.177
      NODE_PORT: 9093
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.177
    platform: windows/amd64
    ports:
    - 9093:9050
    - 9096:9051
  node8:
    command:
    - entrypoint.bat
    container_name: node8
    environment:
      NODE_IP: 192.168.2.18
      NODE_PORT: 9057
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.18
    platform: windows/amd64
    ports:
    - 9057:9050
    - 9090:9051
  node9:
    command:
    - entrypoint.bat
    container_name: node9
    environment:
      NODE_IP: 192.168.2.175
      NODE_PORT: 9084
    image: gavrielnotbenigoren/node:latest
    networks:
      TOR_NETWORK:
        ipv4_address: 192.168.2.175
    platform: windows/amd64
    ports:
    - 9084:9050
    - 9080:9051
