version: '3.8'

services:
  tor_network_service:  # Define a custom service name for your Tor network
    build:
      context: .  # Use the current directory for the build context
      dockerfile: Dockerfile  # Use your custom Dockerfile to configure the Tor network
    ports:
      - "9050:9050"  # Expose a port for SOCKS5 proxy (default for Tor routing)
      - "9051:9051"  # Optionally expose the control port for Tor, if needed
    environment:
      - TOR_PORT=9050  # Environment variable to make the port configurable
    networks:
      - tor_network  # Attach to a custom network for IP management

networks:
  tor_network:
    driver: bridge  # Use bridge mode to control IP address assignments