version: '3.8'

networks:
  TOR_NETWORK:
    driver: bridge
    ipam:
      config:
        - subnet: 192.0.0.0/8 

services:
  node1:
    image: eclipse/cpp_gcc
    container_name: node1
    networks:
      - TOR_NETWORK
    ports:
      - "9050:9050"
      - "9051:9051"

  node2:
    image: eclipse/cpp_gcc
    container_name: node2
    networks:
      - TOR_NETWORK
    ports:
      - "9052:9050"
      - "9053:9051"

  # Additional nodes (node3, node4, etc.) can be added here
